### ISSUE TITLE
java.lang.NoSuchMethodError: 'com.google.common.collect.ImmutableMap com.google.common.collect.ImmutableMap$Builder.buildKeepingLast()

### ISSUE THREAD

**Issue by tao-cxs** [GoogleCloudDataproc/flink-bigquery-connector#123]
hi
I tried to run a simple test with flink 1.17 and flink-bigquery-connector 0.2 and got to following exception, 
the test use readAvrosFromQuery api,  this is the dependency in my pom.xml:

 <dependency>
  <groupId>com.google.cloud.flink</groupId>
  <artifactId>flink-1.17-connector-bigquery</artifactId>
  <version>0.2.0</version>
</dependency>

any idea what could be the problem?

thanks
tao

aused by: org.apache.flink.util.FlinkException: Global failure triggered by OperatorCoordinator for 'Source: BQ Source -> Map -> Sink: Print to Std. Out' (operator cbc357ccb763df2852fee8c4fc7d55f2).
        at org.apache.flink.runtime.operators.coordination.OperatorCoordinatorHolder$LazyInitializedCoordinatorContext.failJob(OperatorCoordinatorHolder.java:600)
        at org.apache.flink.runtime.operators.coordination.RecreateOnResetOperatorCoordinator$QuiesceableContext.failJob(RecreateOnResetOperatorCoordinator.java:242)
        at org.apache.flink.runtime.source.coordinator.SourceCoordinatorContext.failJob(SourceCoordinatorContext.java:394)
        at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$10(SourceCoordinator.java:479)
        at org.apache.flink.util.ThrowableCatchingRunnable.run(ThrowableCatchingRunnable.java:40)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: 'com.google.common.collect.ImmutableMap com.google.common.collect.ImmutableMap$Builder.buildKeepingLast()'
        at com.google.common.util.concurrent.Futures.wrapAndThrowUnchecked(Futures.java:1241)
        at com.google.common.util.concurrent.Futures.getUnchecked(Futures.java:1234)
        at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:53)
        at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
        at com.google.cloud.bigquery.storage.v1.BigQueryReadClient.createReadSession(BigQueryReadClient.java:232)
        at com.google.cloud.flink.bigquery.services.BigQueryServicesImpl$StorageReadClientImpl.createReadSession(BigQueryServicesImpl.java:165)
        at com.google.cloud.flink.bigquery.source.split.SplitDiscoverer.discoverSplits(SplitDiscoverer.java:115)
        at com.google.cloud.flink.bigquery.source.split.assigner.BoundedSplitAssigner.discoverSplits(BoundedSplitAssigner.java:53)
        at com.google.cloud.flink.bigquery.source.split.assigner.BigQuerySourceSplitAssigner.openAndDiscoverSplits(BigQuerySourceSplitAssigner.java:105)
        at com.google.cloud.flink.bigquery.source.enumerator.BigQuerySourceEnumerator.start(BigQuerySourceEnumerator.java:80)
        at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$start$1(SourceCoordinator.java:229)
        at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$10(SourceCoordinator.java:465)
        ... 7 more
Caused by: java.lang.NoSuchMethodError: 'com.google.common.collect.ImmutableMap com.google.common.collect.ImmutableMap$Builder.buildKeepingLast()'
        at com.google.api.gax.rpc.RequestParamsBuilder.build(RequestParamsBuilder.java:94)
        at com.google.cloud.bigquery.storage.v1.stub.GrpcBigQueryReadStub.lambda$new$0(GrpcBigQueryReadStub.java:133)
        at com.google.api.gax.rpc.RequestUrlParamsEncoder.encode(RequestUrlParamsEncoder.java:75)
        at com.google.api.gax.grpc.GrpcUnaryRequestParamCallable.futureCall(GrpcUnaryRequestParamCallable.java:60)
        at com.google.api.gax.grpc.GrpcExceptionCallable.futureCall(GrpcExceptionCallable.java:64)
        at com.google.api.gax.rpc.AttemptCallable.call(AttemptCallable.java:87)
        at com.google.api.gax.rpc.RetryingCallable.futureCall(RetryingCallable.java:78)
        at com.google.api.gax.rpc.RetryingCallable.futureCall(RetryingCallable.java:41)
        at com.google.api.gax.tracing.TracedUnaryCallable.futureCall(TracedUnaryCallable.java:75)
        at com.google.api.gax.rpc.UnaryCallable$1.futureCall(UnaryCallable.java:126)
        at com.google.api.gax.rpc.UnaryCallable.futureCall(UnaryCallable.java:87)
        ... 16 more

**Comment by jayehwhyehentee** [comment]
Seems like ImmutableMap is not being found in classpath. Can you share the application code and pom file?
